# Generated by Django 3.2.23 on 2023-11-24 10:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('guide_image', cloudinary.models.CloudinaryField(default='None', max_length=255, verbose_name='image')),
                ('muscle_group', models.CharField(choices=[('BACK', 'BACK'), ('CHEST', 'CHEST'), ('LEGS', 'LEGS'), ('BICEPS', 'BICEPS'), ('TRICEPS', 'TRICEPS'), ('SHOULDERS', 'SHOULDERS'), ('CARDIO', 'CARDIO'), ('ABS', 'ABS')], max_length=10)),
                ('youtube_link', models.CharField(default='None', max_length=200, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'BEGGINER'), (2, 'ADVANCED'), (3, 'EXPERT')], default=1)),
                ('calories_burnt', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('B', 'BOTH')], default='B', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TraineeInfo',
            fields=[
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sex', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('N', 'NEUTRAL')], default='N', max_length=1)),
                ('goal', models.CharField(choices=[('WL', 'WEIGHT LOSE'), ('MG', 'MUSCLE GAIN'), ('DF', 'DEFINITION')], default='WL', max_length=2)),
                ('calories', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('day', models.PositiveIntegerField(default=1)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('logged_date', models.DateField(auto_now=True)),
                ('sets_ideal', models.PositiveIntegerField(default=0)),
                ('sets_actual', models.PositiveIntegerField(default=0)),
                ('reps_ideal', models.PositiveIntegerField(default=0)),
                ('reps_actual', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise', to='plan.exercises')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='plan.traineeinfo')),
            ],
            options={
                'ordering': ['trainee', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('calories_ideal', models.PositiveIntegerField(default=0)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_log', to='plan.traineeinfo')),
            ],
            options={
                'ordering': ['trainee', '-created_date'],
            },
        ),
    ]
