# Generated by Django 3.2.23 on 2023-11-10 14:21

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('guide_image', cloudinary.models.CloudinaryField(default='None', max_length=255, verbose_name='image')),
                ('muscle_group', models.CharField(choices=[('BC', 'BACK'), ('CT', 'CHEST'), ('LG', 'LEGS'), ('BP', 'BICEPS'), ('TP', 'TRICEPS'), ('SH', 'SHOULDERS')], max_length=2)),
                ('youtube_link', models.CharField(default='None', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TraineeInfo',
            fields=[
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('logged_date', models.DateField(auto_now=True)),
                ('sets_ideal', models.PositiveIntegerField(default=0)),
                ('sets_actual', models.PositiveIntegerField(default=0)),
                ('reps_ideal', models.PositiveIntegerField(default=0)),
                ('reps_actual', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise', to='plan.exercises')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='plan.traineeinfo')),
            ],
            options={
                'ordering': ['trainee', '-created_date'],
            },
        ),
    ]
