# Generated by Django 3.2.23 on 2023-11-12 16:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('role', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_url', cloudinary.models.CloudinaryField(default='add', max_length=255, verbose_name='image')),
                ('caption', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='calories_burnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercises',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('B', 'BOTH')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='exercises',
            name='level',
            field=models.IntegerField(choices=[(1, 'BEGGINER'), (2, 'ADVANCED'), (3, 'EXPERT')], default=1),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('N', 'NEUTRAL')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='goal',
            field=models.CharField(choices=[('WL', 'WEIGHT LOSE'), ('MG', 'MUSCLE GAIN'), ('DF', 'DEFINITION')], default='WL', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group',
            field=models.CharField(choices=[('BC', 'BACK'), ('CT', 'CHEST'), ('LG', 'LEGS'), ('BP', 'BICEPS'), ('TP', 'TRICEPS'), ('SH', 'SHOULDERS'), ('CR', 'CARDIO')], max_length=2),
        ),
    ]
