# Generated by Django 3.2.23 on 2023-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='youtube_link',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
