# Generated by Django 3.2.23 on 2023-12-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_exercises_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['created_date']},
        ),
    ]
