# Generated by Django 3.2.23 on 2023-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20231112_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traineeinfo',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group',
            field=models.CharField(choices=[('BC', 'BACK'), ('CT', 'CHEST'), ('LG', 'LEGS'), ('BP', 'BICEPS'), ('TP', 'TRICEPS'), ('SH', 'SHOULDERS'), ('CR', 'CARDIO'), ('AB', 'ABS')], max_length=2),
        ),
    ]
