# Generated by Django 3.2.23 on 2023-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20231113_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group',
            field=models.CharField(choices=[('BACK', 'BACK'), ('CHEST', 'CHEST'), ('LEGS', 'LEGS'), ('BICEPS', 'BICEPS'), ('TRICEPS', 'TRICEPS'), ('SHOULDERS', 'SHOULDERS'), ('CARDIO', 'CARDIO'), ('ABS', 'ABS')], max_length=10),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('calories_ideal', models.PositiveIntegerField(default=0)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_log', to='plan.traineeinfo')),
            ],
            options={
                'ordering': ['trainee', '-created_date'],
            },
        ),
    ]
