# Generated by Django 3.2.23 on 2023-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20231114_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteImages',
        ),
    ]
