# Generated by Django 3.2.23 on 2023-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_delete_siteimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeinfo',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=1200.0, max_digits=5),
            preserve_default=False,
        ),
    ]
