# Generated by Django 3.2.23 on 2023-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_traineeinfo_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeinfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
